import { useState } from "react";
import { CheckCircle2, Copy, Check, RotateCcw, Download, Shield, Sparkles, TrendingUp, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

interface ClassificationResult {
  hsCode: string;
  memo: string;
  confidence?: number;
  partialAccuracy?: string;
  sixDigitMatch?: string;
}

interface ResultCardProps {
  result: ClassificationResult;
  onReset: () => void;
}

export function ResultCard({ result, onReset }: ResultCardProps) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(result.hsCode);
      setCopied(true);
      toast.success("HS Code copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const downloadMemo = () => {
    const content = `# Bio-Classify AI - Classification Result

## HS/TARIC Code: ${result.hsCode}

${result.partialAccuracy ? `### Accuracy: ${result.partialAccuracy}\n` : ""}
---

## Legal Defense Memo

${result.memo}

---

Generated by Bio-Classify AI
**Disclaimer:** Results from external LLM backend – always verify with Revenue/Customs expert. Not official advice.
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `classification-${result.hsCode.replace(/\./g, "")}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Memo downloaded");
  };

  return (
    <section className="py-16 px-6 animate-fade-slide-up">
      <div className="max-w-3xl mx-auto">
        <Card className="glass-card border-success/30 overflow-hidden rounded-2xl">
          <CardHeader className="gradient-success/10 border-b border-success/20 pb-6">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-3">
                <div className="w-14 h-14 rounded-2xl bg-success/20 flex items-center justify-center shadow-sm">
                  <CheckCircle2 className="w-7 h-7 text-success" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-secondary">
                    Classification Result
                  </h2>
                  <p className="text-sm text-muted-foreground">
                    From external LLM backend
                  </p>
                </div>
              </div>
              <Badge variant="outline" className="border-success/30 bg-success/10 text-success gap-1.5 py-1.5 px-3">
                <Shield className="w-4 h-4" />
                Audit-Ready
              </Badge>
            </div>
          </CardHeader>

          <CardContent className="p-6 md:p-8 space-y-8">
            {/* HS Code Display */}
            <div className="text-center py-8 px-6 rounded-2xl gradient-accent border border-primary/20">
              <p className="text-sm font-medium text-muted-foreground mb-3">
                HS/TARIC Code
              </p>
              <div className="flex items-center justify-center gap-4">
                <span className="text-4xl md:text-5xl font-bold text-primary tracking-wider font-mono">
                  {result.hsCode}
                </span>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={copyToClipboard}
                  className="text-muted-foreground hover:text-primary hover-glow rounded-xl"
                  aria-label="Copy HS Code"
                >
                  {copied ? (
                    <Check className="w-6 h-6 text-success" />
                  ) : (
                    <Copy className="w-6 h-6" />
                  )}
                </Button>
              </div>
              
              {/* ATLAS-Style Metrics */}
              {(result.partialAccuracy || result.sixDigitMatch || result.confidence !== undefined) && (
                <div className="flex flex-wrap items-center justify-center gap-3 mt-6 pt-6 border-t border-primary/20">
                  {result.partialAccuracy && (
                    <Badge variant="secondary" className="text-sm py-1.5 px-4 bg-secondary/10 text-secondary gap-2">
                      <TrendingUp className="w-4 h-4" />
                      {result.partialAccuracy}
                    </Badge>
                  )}
                  {result.sixDigitMatch && (
                    <Badge variant="outline" className="text-sm py-1.5 px-4 border-success/30 text-success">
                      6-digit: {result.sixDigitMatch}
                    </Badge>
                  )}
                  {result.confidence !== undefined && (
                    <Badge variant="outline" className="text-sm py-1.5 px-4">
                      Confidence: {Math.round(result.confidence * 100)}%
                    </Badge>
                  )}
                </div>
              )}
            </div>

            {/* Legal Defense Memo */}
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary" />
                <h3 className="text-lg font-bold text-secondary">
                  Legal Defense Memo
                </h3>
              </div>
              
              <div className="p-6 rounded-2xl bg-muted/30 border border-border/50 text-foreground space-y-4 text-sm leading-relaxed whitespace-pre-wrap">
                {result.memo}
              </div>

              {/* Glass Box Badge */}
              <div className="flex items-center justify-center gap-4">
                <Badge variant="secondary" className="gap-2 py-2 px-4 bg-secondary/10">
                  <Shield className="w-4 h-4" />
                  Glass Box AI – Explainable Reasoning
                </Badge>
              </div>
            </div>

            {/* Disclaimer */}
            <div className="flex items-start gap-3 p-4 rounded-xl bg-warning/10 border border-warning/20">
              <AlertTriangle className="w-5 h-5 text-warning flex-shrink-0 mt-0.5" />
              <p className="text-xs text-muted-foreground">
                <strong className="text-warning">Disclaimer:</strong> Results from external LLM backend – always verify with Revenue/Customs expert. Not official legal or tax advice.
              </p>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row gap-3 pt-4">
              <Button
                variant="outline"
                className="flex-1 rounded-xl h-12 hover-glow"
                onClick={onReset}
              >
                <RotateCcw className="w-4 h-4 mr-2" />
                Classify Another
              </Button>
              <Button
                variant="success"
                className="flex-1 rounded-xl h-12 shadow-button hover-scale-sm"
                onClick={downloadMemo}
              >
                <Download className="w-4 h-4 mr-2" />
                Download Memo
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
