import { useState, useRef, useEffect } from "react";
import {
  CheckCircle2,
  Copy,
  Check,
  RotateCcw,
  Download,
  Shield,
  Sparkles,
  TrendingUp,
  AlertTriangle,
  MessageCircle,
  Send,
  ExternalLink,
  Database,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { askFollowUp } from "@/lib/api";

interface Source {
  code: string;
  description: string;
  url: string;
}

interface ClassificationResult {
  hsCode: string;
  memo: string;
  confidence?: number;
  partialAccuracy?: string;
  sixDigitMatch?: string;
  validationWarning?: string;
  isDemoMode?: boolean;
  sources?: Source[];
  sessionId?: string;
  databaseValidated?: boolean;
}

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

interface ResultCardProps {
  result: ClassificationResult;
  onReset: () => void;
}

export function ResultCard({ result, onReset }: ResultCardProps) {
  const [copied, setCopied] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [isAsking, setIsAsking] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages]);

  const handleAskFollowUp = async () => {
    if (!chatInput.trim() || isAsking) return;

    const question = chatInput.trim();
    setChatInput("");
    setChatMessages((prev) => [...prev, { role: "user", content: question }]);
    setIsAsking(true);

    try {
      const response = await askFollowUp(
        result.sessionId || "",
        question,
        chatMessages,
      );
      setChatMessages((prev) => [
        ...prev,
        { role: "assistant", content: response.response },
      ]);
    } catch (error) {
      toast.error("Failed to get response. Try again.");
      setChatMessages((prev) => prev.slice(0, -1)); // Remove the user message on error
    } finally {
      setIsAsking(false);
    }
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(result.hsCode);
      setCopied(true);
      toast.success("HS Code copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const downloadMemo = () => {
    const content = `# Easy Ship AI - Classification Result

## HS/TARIC Code: ${result.hsCode}

${result.partialAccuracy ? `### Accuracy: ${result.partialAccuracy}\n` : ""}
---

## Legal Defense Memo

${result.memo}

---

Generated by Easy Ship AI
**Disclaimer:** Results from external LLM backend – always verify with Revenue/Customs expert. Not official advice.
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `classification-${result.hsCode.replace(/\./g, "")}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Memo downloaded");
  };

  return (
    <section className="py-16 px-6 animate-fade-slide-up">
      <div className="max-w-3xl mx-auto">
        <Card className="glass-card border-success/30 overflow-hidden rounded-2xl">
          <CardHeader className="gradient-success/10 border-b border-success/20 pb-6">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-3">
                <div className="w-14 h-14 rounded-2xl bg-success/20 flex items-center justify-center shadow-sm">
                  <CheckCircle2 className="w-7 h-7 text-success" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-secondary">
                    Classification Result
                  </h2>
                  <p className="text-sm text-muted-foreground">
                    From external LLM backend
                  </p>
                </div>
              </div>
              <Badge
                variant="outline"
                className="border-success/30 bg-success/10 text-success gap-1.5 py-1.5 px-3"
              >
                <Shield className="w-4 h-4" />
                Audit-Ready
              </Badge>
            </div>
          </CardHeader>

          <CardContent className="p-6 md:p-8 space-y-8">
            {/* Demo Mode Warning */}
            {result.isDemoMode && (
              <div className="flex items-start gap-3 p-4 rounded-xl bg-orange-500/10 border border-orange-500/30">
                <AlertTriangle className="w-5 h-5 text-orange-500 flex-shrink-0 mt-0.5" />
                <div className="text-sm">
                  <p className="font-semibold text-orange-500">
                    Demo Mode Active
                  </p>
                  <p className="text-muted-foreground">
                    Backend API is unavailable. This is a{" "}
                    <strong>simulated classification</strong> based on keyword
                    matching. Connect to the Supabase edge function for real
                    AI-powered classification.
                  </p>
                </div>
              </div>
            )}

            {/* Validation Warning */}
            {result.validationWarning && !result.isDemoMode && (
              <div className="flex items-start gap-3 p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/30">
                <AlertTriangle className="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5" />
                <div className="text-sm">
                  <p className="font-semibold text-yellow-500">
                    Validation Warning
                  </p>
                  <p className="text-muted-foreground">
                    {result.validationWarning}
                  </p>
                </div>
              </div>
            )}

            {/* HS Code Display */}
            <div className="text-center py-8 px-6 rounded-2xl gradient-accent border border-primary/20">
              <p className="text-sm font-medium text-muted-foreground mb-3">
                HS/TARIC Code
              </p>
              <div className="flex items-center justify-center gap-4">
                <span className="text-4xl md:text-5xl font-bold text-primary tracking-wider font-mono">
                  {result.hsCode}
                </span>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={copyToClipboard}
                  className="text-muted-foreground hover:text-primary hover-glow rounded-xl"
                  aria-label="Copy HS Code"
                >
                  {copied ? (
                    <Check className="w-6 h-6 text-success" />
                  ) : (
                    <Copy className="w-6 h-6" />
                  )}
                </Button>
              </div>

              {/* ATLAS-Style Metrics */}
              {(result.partialAccuracy ||
                result.sixDigitMatch ||
                result.confidence !== undefined) && (
                <div className="flex flex-wrap items-center justify-center gap-3 mt-6 pt-6 border-t border-primary/20">
                  {result.partialAccuracy && (
                    <Badge
                      variant="secondary"
                      className="text-sm py-1.5 px-4 bg-secondary/10 text-secondary gap-2"
                    >
                      <TrendingUp className="w-4 h-4" />
                      {result.partialAccuracy}
                    </Badge>
                  )}
                  {result.sixDigitMatch && (
                    <Badge
                      variant="outline"
                      className={`text-sm py-1.5 px-4 ${
                        result.sixDigitMatch.toLowerCase().includes("high")
                          ? "border-success/30 text-success"
                          : result.sixDigitMatch.toLowerCase().includes("low")
                            ? "border-orange-500/30 text-orange-500"
                            : "border-yellow-500/30 text-yellow-500"
                      }`}
                    >
                      6-digit: {result.sixDigitMatch}
                    </Badge>
                  )}
                  {result.confidence !== undefined && (
                    <Badge
                      variant="outline"
                      className={`text-sm py-1.5 px-4 ${
                        result.confidence >= 0.85
                          ? "border-success/30 text-success"
                          : result.confidence >= 0.65
                            ? "border-yellow-500/30 text-yellow-500"
                            : "border-orange-500/30 text-orange-500"
                      }`}
                    >
                      Confidence: {Math.round(result.confidence * 100)}%
                    </Badge>
                  )}
                  {result.databaseValidated && (
                    <Badge
                      variant="outline"
                      className="text-sm py-1.5 px-4 border-success/30 text-success gap-1"
                    >
                      <Database className="w-3 h-3" />
                      Database Validated
                    </Badge>
                  )}
                </div>
              )}
            </div>

            {/* Legal Defense Memo */}
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary" />
                <h3 className="text-lg font-bold text-secondary">
                  Legal Defense Memo
                </h3>
              </div>

              <div className="p-6 rounded-2xl bg-muted/30 border border-border/50 text-foreground space-y-4 text-sm leading-relaxed whitespace-pre-wrap">
                {result.memo}
              </div>

              {/* Glass Box Badge */}
              <div className="flex items-center justify-center gap-4">
                <Badge
                  variant="secondary"
                  className="gap-2 py-2 px-4 bg-secondary/10"
                >
                  <Shield className="w-4 h-4" />
                  Glass Box AI – Explainable Reasoning
                </Badge>
              </div>
            </div>

            {/* Sources Section */}
            {(() => {
              const displaySources = result.sources && result.sources.length > 0 
                ? result.sources 
                : [
                    { code: result.hsCode || "3004.90.00.00", description: "Medicaments put up for retail sale", url: "https://ec.europa.eu/taxation_customs/dds2/taric/" },
                    { code: "3004.50.00.00", description: "Medicaments containing vitamins", url: "https://ec.europa.eu/taxation_customs/dds2/taric/" },
                  ];
              return (
              <div className="space-y-3">
                <div className="flex items-center gap-2">
                  <ExternalLink className="w-5 h-5 text-primary" />
                  <h3 className="text-lg font-bold text-secondary">
                    TARIC Sources
                  </h3>
                  {!result.sources && (
                    <Badge variant="outline" className="text-xs text-muted-foreground">
                      Preview
                    </Badge>
                  )}
                </div>
                <div className="space-y-2">
                  {displaySources.map((source, idx) => (
                    <a
                      key={idx}
                      href={source.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-start gap-3 p-3 rounded-xl bg-muted/30 border border-border/50 hover:bg-muted/50 transition-colors"
                    >
                      <Database className="w-4 h-4 text-primary mt-0.5 flex-shrink-0" />
                      <div className="flex-1 min-w-0">
                        <p className="font-mono text-sm font-semibold text-primary">
                          {source.code}
                        </p>
                        <p className="text-xs text-muted-foreground truncate">
                          {source.description}
                        </p>
                      </div>
                      <ExternalLink className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                    </a>
                  ))}
                </div>
              </div>
              );
            })()}

            {/* Follow-up Chat Section */}
            {(result.sessionId || true) && !result.isDemoMode && (
              <div className="space-y-3">
                <Button
                  variant="outline"
                  className="w-full justify-start gap-2 rounded-xl"
                  onClick={() => setChatOpen(!chatOpen)}
                >
                  <MessageCircle className="w-4 h-4" />
                  {chatOpen ? "Hide" : "Ask"} Follow-up Questions
                  {!result.sessionId && (
                    <Badge variant="outline" className="text-xs text-muted-foreground ml-auto">
                      Preview
                    </Badge>
                  )}
                </Button>

                {chatOpen && (
                  <div className="space-y-3 p-4 rounded-xl bg-muted/30 border border-border/50">
                    <p className="text-xs text-muted-foreground">
                      Ask questions about this classification. The AI will only
                      answer TARIC-related queries.
                    </p>

                    {/* Demo message when no session */}
                    {!result.sessionId && chatMessages.length === 0 && (
                      <div className="space-y-3">
                        <div className="p-3 rounded-lg text-sm bg-primary/10 ml-8">
                          <p className="text-xs font-semibold mb-1">You</p>
                          <p className="whitespace-pre-wrap">Why is this classified under 3004 instead of 3002?</p>
                        </div>
                        <div className="p-3 rounded-lg text-sm bg-muted mr-8">
                          <p className="text-xs font-semibold mb-1">TARIC Assistant</p>
                          <p className="whitespace-pre-wrap">Heading 3002 covers immunological products, vaccines, and blood fractions. Your product is a finished medicament in retail packaging, which falls under heading 3004. The key distinction is that 3002 covers active ingredients/biologicals, while 3004 covers formulated medicines ready for patient use.</p>
                        </div>
                        <p className="text-xs text-center text-muted-foreground italic">
                          This is a preview. Full chat will work once backend is configured.
                        </p>
                      </div>
                    )}

                    {/* Chat Messages */}
                    {chatMessages.length > 0 && (
                      <div className="space-y-3 max-h-64 overflow-y-auto">
                        {chatMessages.map((msg, idx) => (
                          <div
                            key={idx}
                            className={`p-3 rounded-lg text-sm ${
                              msg.role === "user"
                                ? "bg-primary/10 ml-8"
                                : "bg-muted mr-8"
                            }`}
                          >
                            <p className="text-xs font-semibold mb-1">
                              {msg.role === "user" ? "You" : "TARIC Assistant"}
                            </p>
                            <p className="whitespace-pre-wrap">{msg.content}</p>
                          </div>
                        ))}
                        <div ref={chatEndRef} />
                      </div>
                    )}

                    {/* Chat Input */}
                    <div className="flex gap-2">
                      <Input
                        placeholder={result.sessionId ? "e.g., Why is this not classified under 3002?" : "Backend not configured yet..."}
                        value={chatInput}
                        onChange={(e) => setChatInput(e.target.value)}
                        onKeyDown={(e) =>
                          e.key === "Enter" && result.sessionId && handleAskFollowUp()
                        }
                        disabled={isAsking || !result.sessionId}
                        className="flex-1"
                      />
                      <Button
                        size="icon"
                        onClick={handleAskFollowUp}
                        disabled={isAsking || !chatInput.trim() || !result.sessionId}
                      >
                        <Send className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Disclaimer */}
            <div className="flex items-start gap-3 p-4 rounded-xl bg-warning/10 border border-warning/20">
              <AlertTriangle className="w-5 h-5 text-warning flex-shrink-0 mt-0.5" />
              <p className="text-xs text-muted-foreground">
                <strong className="text-warning">Disclaimer:</strong> Results
                from external LLM backend – always verify with Revenue/Customs
                expert. Not official legal or tax advice.
              </p>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row gap-3 pt-4">
              <Button
                variant="outline"
                className="flex-1 rounded-xl h-12 hover-glow"
                onClick={onReset}
              >
                <RotateCcw className="w-4 h-4 mr-2" />
                Classify Another
              </Button>
              <Button
                variant="success"
                className="flex-1 rounded-xl h-12 shadow-button hover-scale-sm"
                onClick={downloadMemo}
              >
                <Download className="w-4 h-4 mr-2" />
                Download Memo
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
