import { useState } from "react";
import { CheckCircle2, Copy, Check, RotateCcw, Download, Shield, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

interface ClassificationResult {
  hsCode: string;
  memo: string;
  confidence?: string;
}

interface ResultCardProps {
  result: ClassificationResult;
  onReset: () => void;
}

export function ResultCard({ result, onReset }: ResultCardProps) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(result.hsCode);
      setCopied(true);
      toast.success("HS Code copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  };

  const downloadMemo = () => {
    const content = `# Bio-Classify AI - Classification Result

## HS/TARIC Code: ${result.hsCode}

---

## Legal Defense Memo

${result.memo}

---

Generated by Bio-Classify AI
Disclaimer: AI assistance only. Always verify with Revenue/Customs expert. Not official advice.
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `classification-${result.hsCode.replace(/\./g, "")}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Memo downloaded");
  };

  return (
    <section className="py-16 px-6 animate-fade-in-up">
      <div className="max-w-3xl mx-auto">
        <Card className="shadow-card-hover border-success/30 overflow-hidden">
          <CardHeader className="bg-success/5 border-b border-success/20 pb-6">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-full bg-success/10 flex items-center justify-center">
                  <CheckCircle2 className="w-6 h-6 text-success" />
                </div>
                <div>
                  <h2 className="text-xl font-semibold text-foreground">
                    Classification Result
                  </h2>
                  <p className="text-sm text-muted-foreground">
                    Analysis complete
                  </p>
                </div>
              </div>
              <Badge variant="outline" className="border-success/30 bg-success/5 text-success gap-1">
                <Shield className="w-3 h-3" />
                Audit-Ready
              </Badge>
            </div>
          </CardHeader>

          <CardContent className="p-6 md:p-8 space-y-8">
            {/* HS Code Display */}
            <div className="text-center py-6 px-4 rounded-xl bg-accent/50 border border-primary/10">
              <p className="text-sm font-medium text-muted-foreground mb-2">
                HS/TARIC Code
              </p>
              <div className="flex items-center justify-center gap-3">
                <span className="text-4xl md:text-5xl font-bold text-primary tracking-wide font-mono">
                  {result.hsCode}
                </span>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={copyToClipboard}
                  className="text-muted-foreground hover:text-primary"
                  aria-label="Copy HS Code"
                >
                  {copied ? (
                    <Check className="w-5 h-5 text-success" />
                  ) : (
                    <Copy className="w-5 h-5" />
                  )}
                </Button>
              </div>
            </div>

            {/* Legal Defense Memo */}
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary" />
                <h3 className="text-lg font-semibold text-foreground">
                  Legal Defense Memo
                </h3>
              </div>
              
              <div className="prose prose-sm max-w-none dark:prose-invert">
                <div className="p-5 rounded-xl bg-muted/30 border border-border/50 text-foreground space-y-4 text-sm leading-relaxed whitespace-pre-wrap">
                  {result.memo}
                </div>
              </div>

              {/* Glass Box Badge */}
              <div className="flex items-center justify-center">
                <Badge variant="secondary" className="gap-1.5 py-1.5 px-3">
                  <Shield className="w-3.5 h-3.5" />
                  Glass Box AI – Explainable Reasoning
                </Badge>
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row gap-3 pt-4">
              <Button
                variant="outline"
                className="flex-1"
                onClick={onReset}
              >
                <RotateCcw className="w-4 h-4 mr-2" />
                Classify Another
              </Button>
              <Button
                variant="success"
                className="flex-1"
                onClick={downloadMemo}
              >
                <Download className="w-4 h-4 mr-2" />
                Download Memo
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
